# Controller generated by Typus, use it to extend admin functionality.
class Admin::PaymentSystemsController < Admin::MasterController

=begin

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   PaymentSystem:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     PaymentSystem: create, read, update, destroy, custom_action
  #
  #   editor:
  #     PaymentSystem: create, read, update, custom_action_for_an_item
  #

  def index
  end

  def custom_action
  end

  def custom_action_for_an_item
  end

=end
  def new
    @payment_system = PaymentSystem.new
    render :action => :edit
  end
  
  def edit
    @payment_system = PaymentSystem.find params[:id]
  end
  
  def update
    @payment_system = PaymentSystem.find params[:id]
    if @payment_system.update_attributes params[:payment_system]
      flash[:notice] = 'Платежная система успешно обновлена'
  else
      flash[:error] = 'Платежная система не обновлена'
  end
    redirect_to admin_payment_systems_path
  end

end
