# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Claim:
  fields:
    list: id, created_at, state, summa, receivable_receive, email, service_fee,
          currency_source, currency_receiver
    show: summa, comment, state, email, fee, service_fee, receivable_source, receivable_receive, md5, currency_receiver, path_way, currency_source, option_purse, request_options, payment_options, response_transfert, errors_claim
  order_by: 
  relationships: currency_receiver, currency_source, path_way, events
  filters: created_at
  search: email
  application: changer

Currency:
  fields:
    list: name, code, payment_system
    form: name, code, description, payment_system
  order_by: 
  relationships: payment_system
  filters: 
  search: name
  application: changer

PathWay:
  fields:
    list: currency_source, currency_receiver, rate, fee, fee_payment_system
    form: currency_source, currency_receiver, rate, fee, fee_payment_system, description
  order_by: 
  relationships: currency_receiver, currency_source
  filters: 
  search: 
  application: changer

PaymentSystem:
  fields:
    list: name, controller
    form: name, description, controller, parameters
  order_by:
  relationships: currencies
  filters: 
  search: name
  application: changer

Event:
  fields:
    list: message, created_at
    form: message, created_at, parameters
    order_by: 
  relationships: claim
  filters: 
  search: messages

SystemSetting:
  fields:
    list: code, name
    form: name, setting
    order_by: 
  filters: 
  search: name
  application: changer


